export const CHANGE_FILTER = "CHANGE_FILTER";
export const ADD_TEXT = "ADD_TEXT";
export const CHANGE_FONT_SIZE = "CHANGE_FONT_SIZE";
export const CHANGE_FONT_FAMILY = "CHANGE_FONT_FAMILY";
export const CHANGE_FONT_COLOR = "CHANGE_FONT_COLOR";
export const CHANGE_FONT_DETAILS = "CHANGE_FONT_DETAILS";

export const CHANGE_CURRENT_TEXT = "CHANGE_CURRENT_TEXT";
