export const CHANGE_FILTER = "CHANGE_FILTER";
export const ADD_TEXT = "ADD_TEXT";
export const CHANGE_FONT_SIZE = "CHANGE_FONT_SIZE";
export const CHANGE_FONT_FAMILY = "CHANGE_FONT_FAMILY";
export const CHANGE_FONT_COLOR = "CHANGE_FONT_COLOR";
export const CHANGE_FONT_BG_COLOR = "CHANGE_FONT_BG_COLOR";
export const CHANGE_FONT_DETAILS = "CHANGE_FONT_DETAILS";
export const CHANGE_FONT_ALIGN = "CHANGE_FONT_ALIGN";
export const CHANGE_FONT_TRANSFORM = "CHANGE_FONT_TRANSFORM";
export const CHANGE_BORDER_COLOR = "CHANGE_BORDER_COLOR";
export const CHANGE_PADDING = "CHANGE_PADDING";

export const CHANGE_CURRENT_TEXT = "CHANGE_CURRENT_TEXT";
export const REMOVE_CURRENT_TEXT = "REMOVE_CURRENT_TEXT";
export const EMPTY_CURRENT_TEXT = "EMPTY_CURRENT_TEXT";
